# Generated by Django 5.1.4 on 2024-12-29 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Friend', 'verbose_name_plural': 'Friends'},
        ),
    ]
