# Generated by Django 5.1.4 on 2024-12-31 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_category_alter_profile_date_of_birth_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
